[package]
name = "grain_kernel"
version = "0.1.0"
authors = ["dinhngtu <dinhngtu@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
