[package]
name = "grain_kernel"
version = "0.1.0"
authors = ["dinhngtu <dinhngtu@users.noreply.github.com>"]
edition = "2018"

[lib]
crate-type = ["staticlib"]

[dependencies]
spin = "^0.5.2"

[dependencies.lazy_static]
version = "^1.4.0"
features = ["spin_no_std"]
